#!/bin/bash

if [ -s "source.txt" ]
then
  echo "[-] Skipped origin version source\n"
else
  if [ -d "gradle/wrapper" ]
  then
    rm -rf graddle
    mkdir gradle
    cp -r ../versions/gradle/wrapper gradle
    cp ../version/gradle/gradle-wrapper.properties gradle/wrapper/gradle-wrapper.properties
    cp ../versions/gradle.properties .
    cp ../versions/local.properties .
    cp ../versions/.gitignore .
    printf "[\xE2\x9C\x94] gradle updated\n"
  else
    echo "[-] Skipping a non gradle module"
  fi
fi
