#!/bin/bash

usage() {
	echo "Submodule commiter"
	echo "Usage: ./scripts/git/commit <commit-message>"
	echo "    examples"
	echo "    - ./scripts/commit 'my very greate commit message'"
}

doAction() {
	msg=$1
	./gradlew updateReadMe && ./gradlew dokkaHtmlMultiModule || echo "Not a gradle module"
	git submodule foreach "../scripts/git/individual/commit \"$msg\""

	echo "Entering $(pwd)"
  ./scripts/git/individual/commit "$msg"
}

main() {
	msg=$1;
	if [[ -z "$msg" ]]; then
		usage
	else
		doAction "$msg"
	fi
}

main "$1";