#!/bin/bash

usage() {
	echo "Submodule commiter"
	echo "Usage: ./scripts/commit <commit-message>"
	echo "    examples"
	echo "    - ./scripts/commit 'my very greate commit message'"
}

doAction() {
	msg=$1
	git submodule foreach ../scripts/git/individual/commit -m "$msg"

	echo "Entering $(pwd)"
  ./scripts/git/individual/commit -m $msg
}

main() {
	msg=$1;
	if [[ -z "$msg" ]]; then
		usage
	else
		doAction "$msg"
	fi
}

main $1;