#!/bin/bash

usage() {
	echo "Submodule pusher"
	echo "Usage: ./scripts/git/push <local-branch> <origin-branch>"
	echo "    examples"
	echo "    - ./scripts/git/push dev-george main"
	echo "    - ./scripts/git/push dev-andy main"
}

checkBranch() {
	branch=$1
	git submodule foreach "../scripts/git/individual/check_branch \"$branch\""
	if [ $? -ne 0 ]; then
		exit 1
	else
		./scripts/git/individual/check_branch "$branch"
		if [ $? -ne 0 ]; then
			exit 1
		else
			echo "Done checking branch"
		fi
	fi
}

doAction() {
	local_branch=$1
	origin_branch=$2
	checkBranch $local_branch
	git submodule foreach "../scripts/git/individual/push $local_branch $origin_branch"

	echo "Entering $(pwd)"
	./scripts/git/individual/push $local_branch $origin_branch
}

main() {
	local_branch=$1;
  origin_branch=$2;
  if [[ -z "$local_branch" ]]; then
		usage
	elif [[ -z "$origin_branch" ]]; then
		usage
	else
		doAction "$local_branch" "$origin_branch"
	fi
}

main $1 $2;
