#!/bin/bash

usage() {
	echo "Submodule pusher"
	echo "Usage: ./scripts/git/push <local-branch> <origin-branch>"
	echo "    examples"
	echo "    - ./scripts/push dev-george main"
	echo "    - ./scripts/push dev-andy main"
}

doAction() {
	local_branch=$1
	origin_branch=$2
	git submodule foreach "../scripts/git/.micro_push $local_branch $origin_branch"
	./.micro_push $local_branch $origin_branch
}

main() {
	local_branch=$1;
  origin_branch=$2;
  if [[ -z "$local_branch" ]]; then
		usage
	elif [[ -z "$origin_branch" ]]; then
		usage
	else
		doAction "$local_branch" "$origin_branch"
	fi
}

main $1 $2;