#!/bin/bash

doAction() {
	branch=$1
	res=$(git branch --show-current)
	if [[ "$res" == *"$branch"* ]]; then
		exit 0
	else
		echo "Branch inconvinience at $(pwd)"
		echo "expected: $branch"
		echo "actual  : $res"
		exit 1
	fi
}

doAction "$1";
