#!/bin/bash

doAction() {
	msg=$1
	echo "----------------------------------------------------"
	echo "PWD: $(pwd)"
	echo "Message:    $msg"
	git add .
	git commit -m "$msg" && printf "[\xE2\x9C\x94] Commited\n" || echo '[-] Skipping: Nothing to commit'
	echo "===================================================="
	printf "\n\n"
}

doAction "$1";
