#!/bin/bash

doAction() {
  msg=$1
  echo "----------------------------------------------------"
  git add .
  echo "Commiting: $msg"
	git commit -m "$msg" || echo '[-] Skipping: Nothing to commit'
	printf "\n\n"
}

doAction "$1";