#!/bin/bash

usage() {
	echo "Multimodule gradle runner"
	echo "Usage: ./scripts/gradle/run <command>"
	echo "example: ./scripts/gradle/run updateReadMe"
}

main() {
  command="$1"
  if [[ -z "$command" ]]; then
  	usage
  else
    git submodule foreach "../scripts/gradle/individual/run '$command'"
  fi
}

main "$1"